name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch (e.g. main)"
        type: string
        required: true
        default: main
      version:
        description: "Version (semver, e.g. 1.2.3)"
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_branch }}
          fetch-depth: 0

      - name: Update package.json version
        run: |
          set -euo pipefail
          VERSION="${{ inputs.version }}"
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "version must be like 1.2.3"; exit 1
          fi
          sudo apt-get update -y && sudo apt-get install -y jq
          jq --arg v "$VERSION" '.version=$v' package.json > package.json.tmp && mv package.json.tmp package.json
          echo "Updated version to $VERSION"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ inputs.base_branch }}
          branch: release/v${{ inputs.version }}
          commit-message: "chore(release): v${{ inputs.version }}"
          title: "Release v${{ inputs.version }}"
          body: |
            Automated release PR
            - Base: `${{ inputs.base_branch }}`
            - Branch: `release/v${{ inputs.version }}`
            - package.json version → `${{ inputs.version }}`
          labels: release, automated
          assignees: y-l-mochizuki
